/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package classical;

import static classical.Shift.getChar;
import static classical.Shift.getPos;
import classical.cracker.CrackerUtils;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nc
 */
public class OTP {

  /**
   * Creates a new empty instance of <code>OTP</code>.
   */
  public OTP() {
  }

  public static String enc(String k, String m) {
    if(k.length() == m.length()) {
      m = m.toLowerCase();
      k = k.toLowerCase();
      String c = new String();
      for(int i = 0; i < m.length(); i++) {
        char mi = m.charAt(i);
        char ki = k.charAt(i);
        c += getChar((getPos(mi) + getPos(ki)) % 26);
      }

      return c.toUpperCase();
    }
    return null;
  }

  public static String dec(String k, String c) {
    if(k.length() == c.length()) {
      c = c.toLowerCase();
      k = k.toLowerCase();
      String m = new String();
      for(int i = 0; i < c.length(); i++) {
        char ci = c.charAt(i);
        char ki = k.charAt(i);
        int mod = (getPos(ci) - getPos(ki)) % 26;
        if(mod < 0) mod += 26;
        m += getChar(mod);
      }
      return m.toUpperCase();
    }
    return null;
  }
  
  public static void main(String[] args) throws Exception{
    
    
    for(String s : TEXTOS){
      // o nome deste metodo mudou para countNgram
      System.out.println(CrackerUtils.repetitions(s, 3, 4));
    }

  }
  
  
  
  
  public static final String TEXTOTP1 = "RHTINACZAWXPCQKCPHDMXSRFJAVVNWHZOAZESCQFKVQUPIQFIDODBKTOKASLZRQCLYPENUOGRIDUJLWBXYBHVGXCLNRTULQWDCIEAMVXLEESIVFJTTOEJVCGFNAQJXSZQIYHDHNFWGZBDVSRWYNFYUJFSBFXVMFLBOCWHFWTPUQCGXMVKBLUCSXODJPCJWOMVEVIFAXDJLPPKEVFLDSHHSETLNEZHCSFHZQWGNWBFDVHSDQINMTCOFARXTNELCKPUCKIKZQRSGFWTPZZKKQUBQYLUAEOMNGBQF"; 
  public static final String TEXTOTP2 = "EOIYXFDUATBLIFIVACYWXLILMCRBMZWHJHXDJYOEJQMDGWJRGOKOVGNNNRGPYJKSZHRETCRLXDDYJVJHPKASRLPQMZGMDOMFGVUQPIHVNYMANZXOJHQUHXYEHWEAKOCINYOEOOYCOLBPYEPTIKWOADLHKAXMUEBHQDJEANJKBXCLFQNQIXYMCPKPGJEBDYMLQWTBARFSFYKISJDADMGICKXREJJNJQDDZDWQOGXKZYCGZDJCDXSEXTKPNPNJOGYIYVNEESAJSYKUCLTZMQIEVPTXTEXXNAUNAD";
  public static final String TEXTOTP3 = "SWNBDQVETCAXIIVJGYBTXHGPVWUHKAOULTSHFNADFONVVNWOJLOPZMTNUYTOAUBKLACMSMCBHZGRSOAZRQTFDYDJHVENWHXLMKEZBQLCXIMVGJRERBMGAYSZZWVALMJSSJFOLUMSPLKATYQKWKOVQKNIENGOYWMBWDBPODQOKZXTXXINCMAPCEELTOSSYTUULGANQRDLBJXJVQPZHCPTTWTOMUIPLRBHBKGAIYYLOAMSKOHCIZENTYZGIBYFMNRIVTHJGNTQDHOPVAFHNERIJNXOZIWQDOVFSY";
  public static final String TEXTOTP4 = "SWZUZKDJMYOOCFELLFAJAOXSWDLWEVQBDQWXBQIVTTOQHEKEBMGFKNHBHXYKSIIZSUQMJUXEOYDAXVAMRZITWXMIGCYQUHASJGRGIYDJJRUBHFJJAONULYILWRTDEMVIEDVYKTTZLEQESHGEBCYAPXOVBPOUFIJDEZOUBDVVVMIKMSHSFBVFMRGZVYOOBWNLDTXWHZNQFYRTMDIGRTSMSILUFXCCLEBUQWPGJNBBWNYBLSNELKXBZKKUNMKMHFAYCINMLVNWMSDYQAFRYEXFPUOUZNFGBEMRTN";
  public static final String TEXTOTP5 = "YAGCPYPZJSFJNWVLFKTYZKOUJZRRGVCAFHWDADMQLSNEBIOXLREDCBJGNLYQWPVLYCMEMDAJGTKKQDUBMDBEIWIQERXBXRBCCSWTBPRFUHASDTRMTGBRARYGIPXGRZQWCHSVXCRHGGBNTMGIDWWOUANCCHUBPOQPYNPCIXQPFDRHGTVESYVRYHCJZWOCBKHCXFOWGJERCNUHVBOHWLVWTPFHXFKWRIUNICQLDJOWCCEGAQHXHFQVTVFNAZSWKVBQRWLIQQHBJJGODDVLTBKGLHMFBXHABAOKAH";
  public static final String TEXTOTP6 = "SIPARKSRGJKBXODBSRCOTTKDLHQMBPTIZCNJFWGKCTRDBCJONAGMTCIOHLAKBXZFUWOCYURUQINWXVKHCBGLITHIDZJZMXHDXLKOCMJSMWINDJTDPUCTHEZOQWBTNPIESOVKHQADUOYKEUZKDKONRZZOKFOPHUVJVREBNHHJFNOHDABEPQSCAYPJCTXKZEBCGASVXJMIBCTYJEROQQZABVECYKEDAEXDHOHYJOLKHNMNXVACQYFTIUVOFZLAOOLKHGNGSUMIEQZJSBKKXODRKSSUEORINQKTGJ";
  public static final String TEXTOTP7 = "ASWHCYPFDJQNALQLVSXLLROFXMFVUSLHSNWGLXFTTMINIOQHUZUBZLXPKMFDLBKWAHZKUANIQGDMESUSNCSHXYHVTWLEFQVKFYWZLROJNRTHHWWCNGZVZQAGRTXKMTHSYMHUBKMNQJOAKJWWHJERBOFDGPGDFUYTOGRUHRLGUMYATMUMOWMRYUSRYVJTCMTEQQPYFYKJBUWYKKDFUJXIPVBKYFDCABVEABUBXOWSOTRNXAHIZVQQRNHMQDZOATVNYEIHBOVMGAXZSSVRXENQHSESASXMVWWAHU";
  public static final String TEXTOTP8 = "PYBLGOUOKKYKXGFKNNPBKFPSENGLKQENLQXNRENBSMOSEIPNWMPYJHCHTOQVMQGMCSNUSLZFZMRMWGNGIGVZWEHUWLUUHECNLWJLVJQSMRWMJOWIHTXOZLIPQEQFBIMRANSKCEGCUAWECMYTSKAMVLXMXKZKPHITDICHGAZHJENYMUGDUBCKOFWJQKTPGBEFHDIHMDSMGVBCBVDTTYIYOZITYMEYASPAHRWJKIGMOMFBVBIZECZDUTRVZMIZVAGMWGGWKESBMLZFCHQNUTELXGGEFDDDSLLPGD";
  public static final String TEXTOTP9 = "EZHDUMIRNCCTIPFZFYOCJYYOLPGOTDUVYPAIRJZFPLZYQSXXWSJUDBEPRYKTMMXVSPSCTBAIBQPRGQZYIJDDYJYDTDSYXIBQBJMEZVVNAMDLXSVAMTXQCJSMLKOXXJNVYXIZXRSDKLMUMCHNAKAYZQJDQMACMSBNFJJMUDTLDSIOCDJORLUWZTHJPNSLEVDERRJQZCCKHPPUVIUOVKCWUGJLOOBUEWGEEWBPRRXOZMWFNBTOHWHGLJHEKHOHNPZVBGSYKHQEJUVFWPURWJNASJGFEBSJWIFHCB";
  public static final String TEXTOTP10 = "ZCIQKYYDJLJOGVIZTYFVHPLJZOTBUJZOSWMPUYSRDOBEBVQUFDSCJGECQVNKNSGSASGNZEDKAYJQSRQVPAVAALZBCQNZUTNDTDLKAZSHVHCPFUINNAGUVWVNXKSSNYWYFJMQMTBAQULTYRQZDZXZIVAOAPXGGHTBGEDFKLDCOLKYKOOGFVRYMCDCHFNPAZBIRRMDXRXMOAWPIINGLTAFBAFXRNGRWYQEBVPGZIEEXTKNJMYTFERQGNAYOKVUNIBJHBCUUMAUPCNXORTIKDRRBKFPVTDXJAWUAM";
  public static final String TEXTOTP11 = "MRPLDJCGUZVVOBZCOBZRNGDGCDCCVLBLQVENFOROGCZDISERHVIRELKSUAKYUEDQFQHMVAKKYPVXLYIMGZYFTBNXWQRVNFZDIWIXHQNKVPCMIQEMTJYQEETIZRBEBZNDPBEXTSRHDHHMJCWYKEKWYPTCCJUYBXQFFULCHZXORFGHKWBKOZHHWOABAEXYOTRLWVHJNDJMFIWGGPVUHRSTRDXRHNHJGXMPHVHUOIKUOJRGFMEYCWCZAQWSNXJCNBREUKVMTZHGERQHGSPXECOHWJAGASXDRURMLU";
  public static final String TEXTOTP12 = "DENHAXEKWUVMXEZOYMKPYPRUZOPCGDZIVNVJFBIDKACVJDOLMVXQHPDCQBBELRNIKEBYEIPHYLDVRUHVVGEKNSEPQOEFLUXSCSRKUJGGKYGHAJWSKPDENXFDDRAHJLRBGAJVPQVPKOEXNXRDMFWIBOBYYZFHHMTFJDAWLIRNADLOZFFAYGVIEKDMSKRCKUUHYGMYPLQMJYHMXQIGYOIWIHFVNKIRQUSIKMUXGYRLFGVNGUWUHAFKUVFGPTIGTGKASPDHTZPGAUJDDMFDSFOODPJDHPHXNCXXEB";
  public static final String TEXTOTP13 = "VRSMEBAOLNHMWWLIDTXOLUDSCKWUDFUBLTZQDQPISBBUQFVHTBGNIKHHKZEDGAYAOVDNFJFGIJAGPSXBZSBWDVHBNPQXPZUGYSFHUZKEURTISEPBCSMUERYECDPFJIULNWEESFMHJOXNVCBXDUZSPGKZPBXPMISZZITNXWWGDIFAXOVGLQAQBPWLQHDCHOKFCVJOMHWWSSANQOVJSMIDAQPSFOCIULLRDBSUFTOYSVRAXUQQZRYABGIOLIKXLLTIICGOWMPLNNPZNZZIIIQINPFCXTIOHXHQVR";
  public static final String TEXTOTP14 = "OHBWHLTNCVVFQZUXYJYGMTCUCXTYXWXLFKYLQYGYIALTGPCUOPBABOMALBYECNCSAAXVAEHGPGIXPKMPRZHWPLONPJZNIQSPOSWSSXWKKFGQJJTYZAKWPBIXQZMDXVKRQYSOULZRPXWGYSRLSXQMSQFXWZKQMKVAPRMTKLHXXPUSJAOCLSUZPZUIFSDNTSDCKZJQIWEHYWDPLPQTGXAGZRSRVXQNOGJMXIVDQADKTPLPWYBNEIDSUEEMXEGDXKXBHCLKHSTHIAMCAPUVDEWUDYQNYYZTWPSETG";
  public static final String TEXTOTP15 = "IYXDJNGDMTBEJWOCBEPNRJYEJMZVBRDGTETVPGZEWWMGJQUHYBOMRJPNMUBSVPYMDBKAWQCMKUPJPUJYYFCSSYDLDRRWAYMKNJUGOLPXWYPRVEKLOECVNNHABYQOXAKXXBJASMNKSMMTDKNFLAPLJNLWVGVKQJQQPQIQYOGZNCHGZZXHEDSRCTKQBGCKJEBHFUCPDSJBIJQELPFVDQCANYNOSECQVHDHSWKBDFYGHQMEIEDERRVKLTMIEZYRMYJEKBNWWZLJGQNSVQTEZPYJUSMIQXMIIWXFVT";
  public static final String TEXTOTP16 = "HKZIYOSBMHPOHOWMRHTIENSCHJQNZQEFELQAXTUAFGXCLGESEMHVPRNYEACFGUNZIQJENGYIYWMEOXSJLWBSWWFOSVSCNDGAFAZECWQZBYGGXKEYTRWOMNWXLXHMOVYWMNSRTJKOZFOOUCBTIQJEXFDWVBCCDXDSPFBJVNTYGVGKBMYBXOIZYEIYFZGLBIWNBHUPHYOBSEAVQIHFCBQRPWMBLMQBKDVQZIBNYJYEZRMLJMAKCGMHALBOSOETRAGBZWFXKDRYRSLQMDDRRMOJKLOEGOYWZCYOST";
  public static final String TEXTOTP17 = "FAKIWAHNUASFHVLAUSJIPLWPNAARZMCFPWFKNNASMNLETGPSLOOLQNVDJWEIHOMBCOEVXIVIKTUPLDQNCTQGMBDEDZSHMZNLSFJNPWFLFDUMJINCMMBROYHOMRUMNYBOWUGCGTEGYUJCQCCVBMQRYFIIDIKRXSKKWDIUEAWIYJSFKEFGLAYVVDEYXQQQTQBBDPXCFHKGMQZZSNLBEZGGUGFLHYSDXVJPADEWBACJBJZSCJEUDPXZDWJEAOVPJGMSREXWCTEXLXJOSEPZIVPPKJPFNXATQQNBGP";
  public static final String TEXTOTP18 = "FEEDIEYEBTGTOWYBUNSDSFHMFMFNWLQUKSDSAVCGTBRZZMEOWFIPGYMJDFTSFGTBPVMEPOAXJZNBLZUWNRFGWWHEPUTNKQXFQFGSHQOSXPYIWXUVXVXEXIYYMRCEIAEPCZTDCWRHYCLYTUOGPJNHETRJOYNEWTWCAHVEUFGUNPHOZWSWULAJUVALBEQVUWTGUXUBGUCMBQNEWSMZVMTYTLHDTZKTAGRJANZYXIYKNMEQMMRAQLCUJNPFFYBSTDQDOEROEFBJZEFWMPOJBMZXRWOLKJWLGAJNCL";
  public static final String TEXTOTP19 = "IBRCYIAIRODCKCOROCVCRSCCDJTTZNRMYREQPIDBRQKBTQGYFWCAROIRRUBWSLOBBAUZMBARUYVWWHLSIGCOTFZLQINZLGXFDAMENDYLZYBQYRQFTAHGEWGBNCXDHNBOLMUJAPBPFGRQRGUOXJZMMULJHDFXXECHKAJRRXRWNVTVNLUNBBALWLRQTJASNEMLBJVXKRVUVNUFEAVDNQPUXSYXTFNJGXZJVTLDWXBBIRLYITHKKZESVGGVYYXPPRJDPEJMDVYFWRWVRUXXYGLIYOTYMBENSPJVDY";
  public static final String TEXTOTP20 = "WVSAKLLAVNGTNLMEBAWXHGQIQSYDGKVBLBSVZSMLJSWBIVYWTUBSPOHQPLOLDWIVPMOYWSDCXYXYOOYCOUGEWLTFZRJEZASOGPTRYNCLYVQGEXARHHRSPZVBNAQYDXHFFZCWYECFANOAHWQCDSMNUJNFHKJXHENQFZZFWRLQHUSWTBUBMOMEEWBPCQJFUBWYDVMIZWNOPDBTNMRWUBTNOVKIFJFBJJBDAEZWWJWVOCUPBTRKTDINVPDUHIBSDYLOVXRZYLFFWPNVBNAMKQRCTDYDHIUYWQOSVQ";

  public static final List<String> TEXTOS = new ArrayList<String>();
  static{
    TEXTOS.add(TEXTOTP1);
    TEXTOS.add(TEXTOTP2);
    TEXTOS.add(TEXTOTP3);
    TEXTOS.add(TEXTOTP4);
    TEXTOS.add(TEXTOTP5);
    TEXTOS.add(TEXTOTP6);
    TEXTOS.add(TEXTOTP7);
    TEXTOS.add(TEXTOTP8);
    TEXTOS.add(TEXTOTP9);
    TEXTOS.add(TEXTOTP10);
    TEXTOS.add(TEXTOTP11);
    TEXTOS.add(TEXTOTP12);
    TEXTOS.add(TEXTOTP13);
    TEXTOS.add(TEXTOTP14);
    TEXTOS.add(TEXTOTP15);
    TEXTOS.add(TEXTOTP16);
    TEXTOS.add(TEXTOTP17);
    TEXTOS.add(TEXTOTP18);
    TEXTOS.add(TEXTOTP19);
    TEXTOS.add(TEXTOTP20);
    
  }


}
