/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package classical;

import static classical.Shift.getChar;
import static classical.Shift.getPos;
import classical.cracker.CrackerUtils;
import classical.cracker.Language;
import classical.cracker.VigenereCrack;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nc
 */
public class OTP {

  /**
   * Creates a new empty instance of <code>OTP</code>.
   */
  public OTP() {
  }

  public static String enc(String k, String m) {
    if(k.length() == m.length()) {
      m = m.toLowerCase();
      k = k.toLowerCase();
      String c = new String();
      for(int i = 0; i < m.length(); i++) {
        char mi = m.charAt(i);
        char ki = k.charAt(i);
        c += getChar((getPos(mi) + getPos(ki)) % 26);
      }

      return c.toUpperCase();
    }
    return null;
  }

  public static String dec(String k, String c) {
    if(k.length() == c.length()) {
      c = c.toLowerCase();
      k = k.toLowerCase();
      String m = new String();
      for(int i = 0; i < c.length(); i++) {
        char ci = c.charAt(i);
        char ki = k.charAt(i);
        int mod = (getPos(ci) - getPos(ki)) % 26;
        if(mod < 0) mod += 26;
        m += getChar(mod);
      }
      return m.toUpperCase();
    }
    return null;
  }
  
  public static void main(String[] args) throws Exception{
    
    System.out.println(OTP.dec("XMCKL", OTP.enc("XMCKL", "HELLO")));

  }
  
  
  
  
  public static final String TEXTO01 = "RHTINACZAWXPCQKCPHDMXSRFJAVVNWHZOAZESCQFKVQUPIQFIDODBKTOKASLZRQCLYPENUOGRIDUJLWBXYBHVGXCLNRTULQWDCIEAMVXLEESIVFJTTOEJVCGFNAQJXSZQIYHDHNFWGZBDVSRWYNFYUJFSBFXVMFLBOCWHFWTPUQCGXMVKBLUCSXODJPCJWOMVEVIFAXDJLPPKEVFLDSHHSETLNEZHCSFHZQWGNWBFDVHSDQINMTCOFARXTNELCKPUCKIKZQRSGFWTPZZKKQUBQYLUAEOMNGBQF";
  public static final String TEXTO02 = "EOIYXFDUATBLIFIVACYWXLILMCRBMZWHJHXDJYOEJQMDGWJRGOKOVGNNNRGPYJKSZHRETCRLXDDYJVJHPKASRLPQMZGMDOMFGVUQPIHVNYMANZXOJHQUHXYEHWEAKOCINYOEOOYCOLBPYEPTIKWOADLHKAXMUEBHQDJEANJKBXCLFQNQIXYMCPKPGJEBDYMLQWTBARFSFYKISJDADMGICKXREJJNJQDDZDWQOGXKZYCGZDJCDXSEXTKPNPNJOGYIYVNEESAJSYKUCLTZMQIEVPTXTEXXNAUNAD";
  public static final String TEXTO03 = "SWNBDQVETCAXIIVJGYBTXHGPVWUHKAOULTSHFNADFONVVNWOJLOPZMTNUYTOAUBKLACMSMCBHZGRSOAZRQTFDYDJHVENWHXLMKEZBQLCXIMVGJRERBMGAYSZZWVALMJSSJFOLUMSPLKATYQKWKOVQKNIENGOYWMBWDBPODQOKZXTXXINCMAPCEELTOSSYTUULGANQRDLBJXJVQPZHCPTTWTOMUIPLRBHBKGAIYYLOAMSKOHCIZENTYZGIBYFMNRIVTHJGNTQDHOPVAFHNERIJNXOZIWQDOVFSY";
  public static final String TEXTO04 = "SWZUZKDJMYOOCFELLFAJAOXSWDLWEVQBDQWXBQIVTTOQHEKEBMGFKNHBHXYKSIIZSUQMJUXEOYDAXVAMRZITWXMIGCYQUHASJGRGIYDJJRUBHFJJAONULYILWRTDEMVIEDVYKTTZLEQESHGEBCYAPXOVBPOUFIJDEZOUBDVVVMIKMSHSFBVFMRGZVYOOBWNLDTXWHZNQFYRTMDIGRTSMSILUFXCCLEBUQWPGJNBBWNYBLSNELKXBZKKUNMKMHFAYCINMLVNWMSDYQAFRYEXFPUOUZNFGBEMRTN";
  public static final String TEXTO05 = "YAGCPYPZJSFJNWVLFKTYZKOUJZRRGVCAFHWDADMQLSNEBIOXLREDCBJGNLYQWPVLYCMEMDAJGTKKQDUBMDBEIWIQERXBXRBCCSWTBPRFUHASDTRMTGBRARYGIPXGRZQWCHSVXCRHGGBNTMGIDWWOUANCCHUBPOQPYNPCIXQPFDRHGTVESYVRYHCJZWOCBKHCXFOWGJERCNUHVBOHWLVWTPFHXFKWRIUNICQLDJOWCCEGAQHXHFQVTVFNAZSWKVBQRWLIQQHBJJGODDVLTBKGLHMFBXHABAOKAH";
  public static final String TEXTO06 = "SIPARKSRGJKBXODBSRCOTTKDLHQMBPTIZCNJFWGKCTRDBCJONAGMTCIOHLAKBXZFUWOCYURUQINWXVKHCBGLITHIDZJZMXHDXLKOCMJSMWINDJTDPUCTHEZOQWBTNPIESOVKHQADUOYKEUZKDKONRZZOKFOPHUVJVREBNHHJFNOHDABEPQSCAYPJCTXKZEBCGASVXJMIBCTYJEROQQZABVECYKEDAEXDHOHYJOLKHNMNXVACQYFTIUVOFZLAOOLKHGNGSUMIEQZJSBKKXODRKSSUEORINQKTGJ";
  public static final String TEXTO07 = "ASWHCYPFDJQNALQLVSXLLROFXMFVUSLHSNWGLXFTTMINIOQHUZUBZLXPKMFDLBKWAHZKUANIQGDMESUSNCSHXYHVTWLEFQVKFYWZLROJNRTHHWWCNGZVZQAGRTXKMTHSYMHUBKMNQJOAKJWWHJERBOFDGPGDFUYTOGRUHRLGUMYATMUMOWMRYUSRYVJTCMTEQQPYFYKJBUWYKKDFUJXIPVBKYFDCABVEABUBXOWSOTRNXAHIZVQQRNHMQDZOATVNYEIHBOVMGAXZSSVRXENQHSESASXMVWWAHU";
  public static final String TEXTO08 = "PYBLGOUOKKYKXGFKNNPBKFPSENGLKQENLQXNRENBSMOSEIPNWMPYJHCHTOQVMQGMCSNUSLZFZMRMWGNGIGVZWEHUWLUUHECNLWJLVJQSMRWMJOWIHTXOZLIPQEQFBIMRANSKCEGCUAWECMYTSKAMVLXMXKZKPHITDICHGAZHJENYMUGDUBCKOFWJQKTPGBEFHDIHMDSMGVBCBVDTTYIYOZITYMEYASPAHRWJKIGMOMFBVBIZECZDUTRVZMIZVAGMWGGWKESBMLZFCHQNUTELXGGEFDDDSLLPGD";
  public static final String TEXTO09 = "EZHDUMIRNCCTIPFZFYOCJYYOLPGOTDUVYPAIRJZFPLZYQSXXWSJUDBEPRYKTMMXVSPSCTBAIBQPRGQZYIJDDYJYDTDSYXIBQBJMEZVVNAMDLXSVAMTXQCJSMLKOXXJNVYXIZXRSDKLMUMCHNAKAYZQJDQMACMSBNFJJMUDTLDSIOCDJORLUWZTHJPNSLEVDERRJQZCCKHPPUVIUOVKCWUGJLOOBUEWGEEWBPRRXOZMWFNBTOHWHGLJHEKHOHNPZVBGSYKHQEJUVFWPURWJNASJGFEBSJWIFHCB";
  public static final String TEXTO10 = "ZCIQKYYDJLJOGVIZTYFVHPLJZOTBUJZOSWMPUYSRDOBEBVQUFDSCJGECQVNKNSGSASGNZEDKAYJQSRQVPAVAALZBCQNZUTNDTDLKAZSHVHCPFUINNAGUVWVNXKSSNYWYFJMQMTBAQULTYRQZDZXZIVAOAPXGGHTBGEDFKLDCOLKYKOOGFVRYMCDCHFNPAZBIRRMDXRXMOAWPIINGLTAFBAFXRNGRWYQEBVPGZIEEXTKNJMYTFERQGNAYOKVUNIBJHBCUUMAUPCNXORTIKDRRBKFPVTDXJAWUAM";
  public static final String TEXTO11 = "MRPLDJCGUZVVOBZCOBZRNGDGCDCCVLBLQVENFOROGCZDISERHVIRELKSUAKYUEDQFQHMVAKKYPVXLYIMGZYFTBNXWQRVNFZDIWIXHQNKVPCMIQEMTJYQEETIZRBEBZNDPBEXTSRHDHHMJCWYKEKWYPTCCJUYBXQFFULCHZXORFGHKWBKOZHHWOABAEXYOTRLWVHJNDJMFIWGGPVUHRSTRDXRHNHJGXMPHVHUOIKUOJRGFMEYCWCZAQWSNXJCNBREUKVMTZHGERQHGSPXECOHWJAGASXDRURMLU";
  public static final String TEXTO12 = "DENHAXEKWUVMXEZOYMKPYPRUZOPCGDZIVNVJFBIDKACVJDOLMVXQHPDCQBBELRNIKEBYEIPHYLDVRUHVVGEKNSEPQOEFLUXSCSRKUJGGKYGHAJWSKPDENXFDDRAHJLRBGAJVPQVPKOEXNXRDMFWIBOBYYZFHHMTFJDAWLIRNADLOZFFAYGVIEKDMSKRCKUUHYGMYPLQMJYHMXQIGYOIWIHFVNKIRQUSIKMUXGYRLFGVNGUWUHAFKUVFGPTIGTGKASPDHTZPGAUJDDMFDSFOODPJDHPHXNCXXEB";
  public static final String TEXTO13 = "VRSMEBAOLNHMWWLIDTXOLUDSCKWUDFUBLTZQDQPISBBUQFVHTBGNIKHHKZEDGAYAOVDNFJFGIJAGPSXBZSBWDVHBNPQXPZUGYSFHUZKEURTISEPBCSMUERYECDPFJIULNWEESFMHJOXNVCBXDUZSPGKZPBXPMISZZITNXWWGDIFAXOVGLQAQBPWLQHDCHOKFCVJOMHWWSSANQOVJSMIDAQPSFOCIULLRDBSUFTOYSVRAXUQQZRYABGIOLIKXLLTIICGOWMPLNNPZNZZIIIQINPFCXTIOHXHQVR";
  public static final String TEXTO14 = "OHBWHLTNCVVFQZUXYJYGMTCUCXTYXWXLFKYLQYGYIALTGPCUOPBABOMALBYECNCSAAXVAEHGPGIXPKMPRZHWPLONPJZNIQSPOSWSSXWKKFGQJJTYZAKWPBIXQZMDXVKRQYSOULZRPXWGYSRLSXQMSQFXWZKQMKVAPRMTKLHXXPUSJAOCLSUZPZUIFSDNTSDCKZJQIWEHYWDPLPQTGXAGZRSRVXQNOGJMXIVDQADKTPLPWYBNEIDSUEEMXEGDXKXBHCLKHSTHIAMCAPUVDEWUDYQNYYZTWPSETG";
  public static final String TEXTO15 = "IYXDJNGDMTBEJWOCBEPNRJYEJMZVBRDGTETVPGZEWWMGJQUHYBOMRJPNMUBSVPYMDBKAWQCMKUPJPUJYYFCSSYDLDRRWAYMKNJUGOLPXWYPRVEKLOECVNNHABYQOXAKXXBJASMNKSMMTDKNFLAPLJNLWVGVKQJQQPQIQYOGZNCHGZZXHEDSRCTKQBGCKJEBHFUCPDSJBIJQELPFVDQCANYNOSECQVHDHSWKBDFYGHQMEIEDERRVKLTMIEZYRMYJEKBNWWZLJGQNSVQTEZPYJUSMIQXMIIWXFVT";
  public static final String TEXTO16 = "HKZIYOSBMHPOHOWMRHTIENSCHJQNZQEFELQAXTUAFGXCLGESEMHVPRNYEACFGUNZIQJENGYIYWMEOXSJLWBSWWFOSVSCNDGAFAZECWQZBYGGXKEYTRWOMNWXLXHMOVYWMNSRTJKOZFOOUCBTIQJEXFDWVBCCDXDSPFBJVNTYGVGKBMYBXOIZYEIYFZGLBIWNBHUPHYOBSEAVQIHFCBQRPWMBLMQBKDVQZIBNYJYEZRMLJMAKCGMHALBOSOETRAGBZWFXKDRYRSLQMDDRRMOJKLOEGOYWZCYOST";
  public static final String TEXTO17 = "FAKIWAHNUASFHVLAUSJIPLWPNAARZMCFPWFKNNASMNLETGPSLOOLQNVDJWEIHOMBCOEVXIVIKTUPLDQNCTQGMBDEDZSHMZNLSFJNPWFLFDUMJINCMMBROYHOMRUMNYBOWUGCGTEGYUJCQCCVBMQRYFIIDIKRXSKKWDIUEAWIYJSFKEFGLAYVVDEYXQQQTQBBDPXCFHKGMQZZSNLBEZGGUGFLHYSDXVJPADEWBACJBJZSCJEUDPXZDWJEAOVPJGMSREXWCTEXLXJOSEPZIVPPKJPFNXATQQNBGP";
  public static final String TEXTO18 = "FEEDIEYEBTGTOWYBUNSDSFHMFMFNWLQUKSDSAVCGTBRZZMEOWFIPGYMJDFTSFGTBPVMEPOAXJZNBLZUWNRFGWWHEPUTNKQXFQFGSHQOSXPYIWXUVXVXEXIYYMRCEIAEPCZTDCWRHYCLYTUOGPJNHETRJOYNEWTWCAHVEUFGUNPHOZWSWULAJUVALBEQVUWTGUXUBGUCMBQNEWSMZVMTYTLHDTZKTAGRJANZYXIYKNMEQMMRAQLCUJNPFFYBSTDQDOEROEFBJZEFWMPOJBMZXRWOLKJWLGAJNCL";
  public static final String TEXTO19 = "IBRCYIAIRODCKCOROCVCRSCCDJTTZNRMYREQPIDBRQKBTQGYFWCAROIRRUBWSLOBBAUZMBARUYVWWHLSIGCOTFZLQINZLGXFDAMENDYLZYBQYRQFTAHGEWGBNCXDHNBOLMUJAPBPFGRQRGUOXJZMMULJHDFXXECHKAJRRXRWNVTVNLUNBBALWLRQTJASNEMLBJVXKRVUVNUFEAVDNQPUXSYXTFNJGXZJVTLDWXBBIRLYITHKKZESVGGVYYXPPRJDPEJMDVYFWRWVRUXXYGLIYOTYMBENSPJVDY";
  public static final String TEXTO20 = "WVSAKLLAVNGTNLMEBAWXHGQIQSYDGKVBLBSVZSMLJSWBIVYWTUBSPOHQPLOLDWIVPMOYWSDCXYXYOOYCOUGEWLTFZRJEZASOGPTRYNCLYVQGEXARHHRSPZVBNAQYDXHFFZCWYECFANOAHWQCDSMNUJNFHKJXHENQFZZFWRLQHUSWTBUBMOMEEWBPCQJFUBWYDVMIZWNOPDBTNMRWUBTNOVKIFJFBJJBDAEZWWJWVOCUPBTRKTDINVPDUHIBSDYLOVXRZYLFFWPNVBNAMKQRCTDYDHIUYWQOSVQ";

  public static String[] TEXTOS = new String[]{
    TEXTO01, TEXTO02, TEXTO03, TEXTO04, TEXTO05, TEXTO06, TEXTO07, TEXTO08, TEXTO09,
    TEXTO10, TEXTO11, TEXTO12, TEXTO13, TEXTO14, TEXTO15, TEXTO16, TEXTO17, TEXTO18,
    TEXTO19, TEXTO20
  };
  


}
